AWSTemplateFormatVersion: '2010-09-09'
Description: 'GA Novelist RDS - 超最小構成（バックアップなし）'

Parameters:
  DBMasterPassword:
    Description: Database password
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    Default: GaNovelist2024!  # 開発用デフォルト（本番では変更必須）

Resources:
  # 最小限のセキュリティグループ
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: GA Novelist RDS SG (ultra minimal)
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0  # 全開放（開発専用）

  # RDSインスタンス（超最小構成）
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete  # スナップショットも作らない
    Properties:
      DBInstanceIdentifier: ga-novelist-ultra-minimal
      DBName: ga_novelist
      
      # PostgreSQL最小構成
      Engine: postgres
      EngineVersion: '15.4'
      DBInstanceClass: db.t3.micro
      
      # ========================================
      # 💰 究極のコスト削減設定
      # ========================================
      
      # ストレージ最小
      AllocatedStorage: 20  # 最小値
      StorageType: gp2      # 最安
      StorageEncrypted: false
      
      # 認証（シンプル）
      MasterUsername: postgres
      MasterUserPassword: !Ref DBMasterPassword
      
      # パブリックアクセス可能（VPN不要）
      PubliclyAccessible: true
      
      # ========================================
      # 🔥 全ての追加機能を無効化
      # ========================================
      
      # バックアップ完全無効
      BackupRetentionPeriod: 0  # バックアップなし
      
      # 監視無効
      EnablePerformanceInsights: false
      MonitoringInterval: 0  # CloudWatch監視なし
      
      # ログ出力無効
      EnableCloudwatchLogsExports: []
      
      # 自動アップグレード無効
      AutoMinorVersionUpgrade: false
      
      # マルチAZ無効
      MultiAZ: false
      
      # 削除保護無効
      DeletionProtection: false
      
      # メンテナンスウィンドウ最短
      PreferredMaintenanceWindow: 'sun:18:00-sun:18:30'

Outputs:
  QuickStart:
    Description: クイックスタートガイド
    Value: !Sub |
      ========================================
      🚀 接続方法
      ========================================
      
      1. psqlで接続:
      psql -h ${DBInstance.Endpoint.Address} -U postgres -d ga_novelist
      
      2. Juliaから接続:
      using LibPQ
      conn = LibPQ.Connection("postgresql://postgres:${DBMasterPassword}@${DBInstance.Endpoint.Address}/ga_novelist")
      
      3. 初期化:
      psql -h ${DBInstance.Endpoint.Address} -U postgres -d ga_novelist -f database/01_create_schema.sql
      
      ========================================
      💰 月額コスト: 約$12（約1,800円）
      ========================================
      - インスタンス: $12.41
      - ストレージ: $2.30
      - バックアップ: $0（無効）
      - 合計: 約$14.71/月
      
      ========================================
      ⚠️ 注意事項
      ========================================
      - バックアップなし（データ消失リスクあり）
      - 監視なし（障害検知できない）
      - 全世界からアクセス可能（セキュリティリスク）
      - 開発専用（本番使用厳禁）